name: Webpage Scraper
#
on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12

      #it is not necessary install firefox on ubuntu

      #This will print the path to the Firefox binary in the action's logs.
      - name: Locate Firefox Binary
        run: |
          which firefox
      
      - name: Test Firefox Launch
        run: |
          /usr/bin/firefox --headless --version

      - name: Check Firefox Binary
        run: |
          ls /usr/bin | grep firefox
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py


      - name: Commit and push changes
        run: |
          git config --local user.email "43762575+fms-1988@users.noreply.github.com"
          git config --local user.name "fms-1988"
          git add data/*.csv
          git commit -m "Add scraped data" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/fms-1988/INMET_frost.git
          git push













      
