name: Webpage Scraper
#
on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Setup Firefox (non-snap version)
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      #This will print the path to the Firefox binary in the action's logs.
      - name: Locate Firefox Binary
        run: |
          which firefox
      
      - name: Test Firefox Launch
        run: |
          /usr/bin/firefox --headless --version

      - name: Check Firefox Binary
        run: |
          ls /usr/bin | grep firefox

      - name: Install dependencies_1
        run: |
          sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 xvfb
          
      - name: Install Dependencies_2
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
